name: vmp-proj
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - jupytext
  - ipykernel
  - matplotlib=3.4.*
  - cartopy=0.20.*
  - numpy=1.21.*
  - scipy=1.7.*
  - pip
  - pip:
      - "git+https://github.com/jessecusack/example_python_package"
  